version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run:
          name: Deploy Master to Heroku
          command: |
            HEROKU_APP_NAME="bifrost-beta"
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
#      - run: go test -v ./.. .

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git