package handler

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"log"
)

type AutoGenerated struct {
	Event     Event   `json:"event"`
	CreatedAt string  `json:"created_at"`
	ID        string  `json:"id"`
	Trigger   Trigger `json:"trigger"`
	Table     Table   `json:"table"`
}
type Data struct {
	Old string `json:"old"`
	New string `json:"new"`
}
type Event struct {
	SessionVariables string `json:"session_variables"`
	Op               string `json:"op"`
	Data             Data   `json:"data"`
}
type Trigger struct {
	Name string `json:"name"`
}
type Table struct {
	Schema string `json:"schema"`
	Name   string `json:"name"`
}

func PostExpense(c *gin.Context) {
	hasura := &AutoGenerated{}
	err := c.Bind(hasura)
	if err != nil {
		log.Fatalln(err)
	}
	fmt.Printf("event: %s", hasura)
}
